const Action = require('../models/Action');
const { logMemory } = require('../utils/projectMemoryLogger');

exports.createAction = async (req, res) => {
  const { title, description, assignee, project, dueDate, status } = req.body;

  if (!title || !assignee || !project) {
    return res.status(400).json({
      error: { message: 'Missing required fields: title, assignee, and project are required' }
    });
  }

  const action = new Action({
    title,
    description,
    assignee,
    project,
    dueDate,
    status,
    isAutoGenerated: false
  });

  await action.save();

  await logMemory({
    projectId: project,
    eventType: 'action_created',
    summary: `Action created: "${title}"`,
    actorType: 'stakeholder',
    actorRef: assignee
  });

  const populated = await Action.findById(action._id).populate('assignee');
  res.status(201).json(populated);
};

exports.getActionById = async (req, res) => {
  const action = await Action.findById(req.params.id).populate('assignee');
  if (!action) {
    return res.status(404).json({ error: { message: 'Action not found' } });
  }
  res.json(action);
};

exports.updateAction = async (req, res) => {
  const { status, assignee, dueDate, title, description } = req.body;
  const action = await Action.findById(req.params.id);

  if (!action) {
    return res.status(404).json({ error: { message: 'Action not found' } });
  }

  const oldStatus = action.status;

  if (title !== undefined) action.title = title;
  if (description !== undefined) action.description = description;
  if (status !== undefined) action.status = status;
  if (assignee !== undefined) action.assignee = assignee;
  if (dueDate !== undefined) action.dueDate = dueDate;

  await action.save();

  if (status === 'done' && oldStatus !== 'done') {
    await logMemory({
      projectId: action.project,
      eventType: 'action_completed',
      summary: `Action completed: "${action.title}"`,
      actorType: 'stakeholder',
      actorRef: action.assignee
    });
  }

  const updated = await Action.findById(action._id).populate('assignee');
  res.json(updated);
};

exports.getProjectActions = async (req, res) => {
  const { projectId } = req.params;

  const actions = await Action.find({
    project: projectId,
    status: { $in: ['open', 'in-progress'] }
  }).populate('assignee');

  // Group by assigneeId
  const grouped = {};
  for (const act of actions) {
    if (!act.assignee) continue;
    const assigneeId = act.assignee._id.toString();

    if (!grouped[assigneeId]) {
      grouped[assigneeId] = {
        assignee: act.assignee,
        actions: []
      };
    }

    grouped[assigneeId].actions.push(act);
  }

  res.json(grouped);
};
