const ChangeEvent = require('../models/ChangeEvent');
const ImpactResult = require('../models/ImpactResult');
const Alert = require('../models/Alert');
const Action = require('../models/Action');
const Activity = require('../models/Activity');
const Approval = require('../models/Approval');
const impactAnalysis = require('../services/impactAnalysis');
const { logMemory } = require('../utils/projectMemoryLogger');

const ALLOWED_TYPES = [
  'material change',
  'design revision',
  'scope change',
  'delay',
  'issue'
];

exports.createChangeEvent = async (req, res) => {
  const { type, description, sourceStakeholder, project, linkedEntities } = req.body;

  if (!type || !description || !sourceStakeholder || !project) {
    return res.status(400).json({
      error: { message: 'Missing required fields: type, description, sourceStakeholder, and project are required' }
    });
  }

  if (!ALLOWED_TYPES.includes(type)) {
    return res.status(400).json({
      error: { message: `Invalid type '${type}'. Must be one of: ${ALLOWED_TYPES.join(', ')}` }
    });
  }

  // 1. Save ChangeEvent
  const changeEvent = new ChangeEvent({
    type,
    description,
    sourceStakeholder,
    project,
    linkedEntities: linkedEntities || []
  });
  await changeEvent.save();

  // 2. Log change_event_created in ProjectMemory
  await logMemory({
    projectId: project,
    eventType: 'change_event_created',
    summary: `Change event logged: "${description}"`,
    actorType: 'stakeholder',
    actorRef: sourceStakeholder
  });

  // 3. Run Impact Analysis
  const analysisResult = await impactAnalysis.run({
    projectId: project,
    startEntities: changeEvent.linkedEntities,
    changeEventId: changeEvent._id,
    changeEventName: description
  });

  // 4. Save ImpactResult
  const impactResult = new ImpactResult({
    changeEvent: changeEvent._id,
    project,
    affectedActivities: analysisResult.affectedActivityIds,
    affectedApprovals: analysisResult.affectedApprovalIds,
    affectedStakeholders: analysisResult.affectedStakeholderIds,
    reasoningChains: analysisResult.reasoningChains
  });
  await impactResult.save();

  // Update change event with reference
  changeEvent.impactResult = impactResult._id;
  await changeEvent.save();

  // 5. Log impact_result_produced
  await logMemory({
    projectId: project,
    eventType: 'impact_result_produced',
    summary: `Impact analysis completed: ${analysisResult.affectedActivityIds.length} activities, ${analysisResult.affectedApprovalIds.length} approvals, and ${analysisResult.affectedStakeholderIds.length} stakeholders affected`,
    actorType: 'system'
  });

  // 6. Bulk-fetch owner mapping for all affected entities
  const [activities, approvals] = await Promise.all([
    Activity.find({ _id: { $in: analysisResult.affectedActivityIds } }).select('name owner').lean(),
    Approval.find({ _id: { $in: analysisResult.affectedApprovalIds } }).select('title owner').lean()
  ]);

  const entityOwnerMap = new Map();
  for (const act of activities) {
    if (act.owner) entityOwnerMap.set(act._id.toString(), act.owner.toString());
  }
  for (const app of approvals) {
    if (app.owner) entityOwnerMap.set(app._id.toString(), app.owner.toString());
  }

  // 7. Create Alerts & auto-generated Actions per affected entity reasoning chain
  for (const chain of analysisResult.reasoningChains) {
    const ownerId = entityOwnerMap.get(chain.entity.toString());
    if (!ownerId) continue;

    // Build human readable reasoning steps
    const readableSteps = chain.steps.map(
      (step) => `${step.fromModel}: ${step.fromName} → ${step.toModel}: ${step.toName}`
    );

    // Create Alert
    await Alert.create({
      stakeholder: ownerId,
      project,
      changeEvent: changeEvent._id,
      changeEventName: description,
      impactResult: impactResult._id,
      affectedEntity: {
        entity: chain.entity,
        model: chain.model,
        name: chain.name
      },
      reasoningChain: readableSteps
    });

    // Create Auto-Generated Action
    const action = await Action.create({
      project,
      title: `Review impact: ${chain.name}`,
      description: `Auto-generated action from change event: ${description}`,
      assignee: ownerId,
      isAutoGenerated: true,
      sourceImpactResult: impactResult._id,
      status: 'open'
    });

    await logMemory({
      projectId: project,
      eventType: 'action_created',
      summary: `Auto-generated action created: "Review impact: ${chain.name}"`,
      actorType: 'system'
    });
  }

  const populatedChangeEvent = await ChangeEvent.findById(changeEvent._id)
    .populate('sourceStakeholder')
    .populate('impactResult');

  res.status(201).json(populatedChangeEvent);
};

exports.getChangeEventById = async (req, res) => {
  const changeEvent = await ChangeEvent.findById(req.params.id)
    .populate('sourceStakeholder')
    .populate('impactResult');

  if (!changeEvent) {
    return res.status(404).json({ error: { message: 'Change event not found' } });
  }

  res.json(changeEvent);
};

exports.getProjectChangeEvents = async (req, res) => {
  const { projectId } = req.params;
  const changeEvents = await ChangeEvent.find({ project: projectId })
    .sort({ timestamp: -1 })
    .populate('sourceStakeholder')
    .populate('impactResult');

  res.json(changeEvents);
};
