import React from 'react';
import StatusBadge from '../shared/StatusBadge';
import { Zap, Calendar, User, CheckCircle2, Clock } from 'lucide-react';

export default function ActionCard({ action, onStatusChange }) {
  if (!action) return null;

  return (
    <div
      className={`p-4 rounded-2xl border backdrop-blur-xl mb-3 transition-all duration-200 group hover:border-slate-700/80 ${
        action.isAutoGenerated
          ? 'bg-gradient-to-r from-sky-500/10 via-slate-900/60 to-slate-900/60 border-sky-500/30 hover:border-sky-500/50 shadow-lg shadow-sky-500/5'
          : 'bg-slate-900/70 border-slate-800/80 hover:bg-slate-900/90 shadow-md'
      }`}
    >
      <div className="flex items-start justify-between gap-3 mb-2">
        <h4 className="text-xs font-bold text-slate-100 leading-snug group-hover:text-sky-300 transition-colors">
          {action.title}
        </h4>
        <StatusBadge status={action.status} />
      </div>

      {action.description && (
        <p className="text-xs text-slate-400 mb-3 leading-relaxed font-normal">
          {action.description}
        </p>
      )}

      <div className="flex items-center justify-between pt-3 border-t border-slate-800/80 text-xs">
        <div className="flex items-center gap-2">
          {action.isAutoGenerated ? (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[9px] font-extrabold uppercase bg-sky-500/15 text-sky-300 border border-sky-500/30 shadow-[0_0_8px_rgba(14,165,233,0.2)]">
              <Zap className="w-2.5 h-2.5 fill-sky-300/40 animate-pulse" />
              Auto-Generated
            </span>
          ) : (
            <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider bg-slate-800/80 px-2 py-0.5 rounded border border-slate-700">
              Manual Action
            </span>
          )}
        </div>

        {onStatusChange && (
          <select
            value={action.status}
            onChange={(e) => onStatusChange(action._id, e.target.value)}
            className="bg-slate-950 border border-slate-800 text-slate-200 text-[11px] rounded-xl px-2.5 py-1 font-bold focus:outline-none focus:border-sky-500 transition-colors shadow-inner"
          >
            <option value="open">Open</option>
            <option value="in-progress">In-Progress</option>
            <option value="done">Done (Complete)</option>
          </select>
        )}
      </div>
    </div>
  );
}

