import React from 'react';
import StatusBadge from '../shared/StatusBadge';
import { Zap, Calendar, User } from 'lucide-react';

export default function ActionCard({ action, onStatusChange }) {
  if (!action) return null;

  return (
    <div
      className={`p-4 rounded-xl border backdrop-blur-md mb-3 transition-all ${
        action.isAutoGenerated
          ? 'bg-sky-500/5 border-sky-500/20 hover:border-sky-500/40'
          : 'bg-slate-900/60 border-slate-800 hover:border-slate-700'
      }`}
    >
      <div className="flex items-start justify-between gap-3 mb-2">
        <h4 className="text-sm font-bold text-slate-100 leading-snug">
          {action.title}
        </h4>
        <StatusBadge status={action.status} />
      </div>

      {action.description && (
        <p className="text-xs text-slate-400 mb-3 leading-relaxed">
          {action.description}
        </p>
      )}

      <div className="flex items-center justify-between pt-3 border-t border-slate-800/80 text-xs">
        <div className="flex items-center gap-2">
          {action.isAutoGenerated ? (
            <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[10px] font-extrabold uppercase bg-sky-500/10 text-sky-400 border border-sky-500/20">
              <Zap className="w-3 h-3 fill-sky-400/30" />
              Auto-Generated
            </span>
          ) : (
            <span className="text-slate-400 font-medium">Manual Action</span>
          )}
        </div>

        {onStatusChange && (
          <select
            value={action.status}
            onChange={(e) => onStatusChange(action._id, e.target.value)}
            className="bg-slate-800 border border-slate-700 text-slate-200 text-xs rounded-lg px-2 py-1 font-medium focus:outline-none focus:border-sky-500 transition-colors"
          >
            <option value="open">Open</option>
            <option value="in-progress">In-Progress</option>
            <option value="done">Done (Complete)</option>
          </select>
        )}
      </div>
    </div>
  );
}
