import mongoose from 'mongoose';

const { Schema } = mongoose;

const ActionSchema = new Schema(
  {
    project: { type: Schema.Types.ObjectId, ref: 'Project', required: true },
    title: { type: String, required: true, trim: true },
    description: { type: String, trim: true },
    assignee: { type: Schema.Types.ObjectId, ref: 'Stakeholder', required: true },
    dueDate: { type: Date },
    status: {
      type: String,
      enum: ['open', 'in-progress', 'done'],
      default: 'open'
    },
    sourceImpactResult: { type: Schema.Types.ObjectId, ref: 'ImpactResult' },
    isAutoGenerated: { type: Boolean, default: false }
  },
  { timestamps: true }
);

ActionSchema.index({ project: 1, status: 1 });
ActionSchema.index({ assignee: 1, status: 1 });

export default mongoose.model('Action', ActionSchema);
